apiVersion: apps/v1
kind: Deployment
metadata:
  name: openspeedtest
  namespace: openspeedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openspeedtest
  template:
    metadata:
      labels:
        app: openspeedtest
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: openspeedtest
        image: openspeedtest/latest:latest
        ports:
        - containerPort: 3000
